CREATE TABLE IF NOT EXISTS base_model (
  id SERIAL PRIMARY KEY,
  CHECK (id > 0)
);

CREATE TABLE IF NOT EXISTS service (
  id INTEGER PRIMARY KEY REFERENCES base_model (id) ON DELETE CASCADE,
  name VARCHAR(50) NOT NULL UNIQUE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ms_update FLOAT NOT NULL DEFAULT 0.25 CHECK (ms_update > 0)
);

CREATE TABLE email (
  id INTEGER PRIMARY KEY REFERENCES service (id) ON DELETE CASCADE,
  imap_server VARCHAR(50),
  pop_server VARCHAR(50)
);

CREATE TABLE email_profile (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR NOT NULL,
  email_id INTEGER REFERENCES email (id) ON DELETE CASCADE
);

CREATE TABLE messenger (
  id INTEGER PRIMARY KEY REFERENCES service (id) ON DELETE CASCADE
);